version: "3.1"

services:
  db:
    container_name: mysql
    hostname: localhost
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: database
    ports:
      - 3306:3306